# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_samc_ex1_R <- function(qpathSEXP) {
    .Call(`_C_SamcPackage_run_samc_ex1_R`, qpathSEXP)
}

